export const LIST_VOICES = "LIST_VOICES";
export const CREATE_AUDIO = "CREATE_AUDIO";
export const LIST_UTTERANCES = "LIST_UTTERANCES";
export const ASYNC_JOBS = "ASYNC_JOBS";
export const ASYNC_STATUS = "ASYNC_STATUS";
export const DOWNLOAD_UTTERANCE = "DOWNLOAD_UTTERANCE";